---
language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/spec/fixtures/modules
before_install: rm Gemfile.lock || true
install:
  - bundle install --without development system_tests --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake spec_prep
script: bundle exec rake test
branches:
  only:
  - master
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
