---
name: 'checks'

'on':
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  static-analysis:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v2.4.0'

      - name: 'Set up Ruby'
        uses: 'ruby/setup-ruby@v1.94.0'
        with:
          ruby-version: '2.4'

      - name: Get full Ruby version
        id: full-ruby-version
        run: |
          echo ::set-output name=version::$(ruby -e 'puts RUBY_VERSION')

      - name: 'Cache Ruby'
        uses: 'actions/cache@v2.1.7'
        with:
          path: 'vendor/bundle'
          key: ${{ runner.os }}-${{ steps.full-ruby-version.outputs.version }}-v1-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.full-ruby-version.outputs.version }}-v1-gems-

      - name: 'Install ruby dependencies'
        run: |
          gem install bundler
          bundler --version
          bundle config path vendor/bundle
          bundle config set with 'development'
          bundle install --jobs 4 --retry 3

      - name: 'Run static analysis'
        run: |
          bundle exec rake check:symlinks
          bundle exec rake check:git_ignore
          bundle exec rake check:dot_underscore
          bundle exec rake check:test_file
          bundle exec rake rubocop
          bundle exec rake syntax
          bundle exec rake lint
          bundle exec rake metadata_lint

  unit-tests:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        exclude:
          - ruby: '2.6'
            puppet: '< 6.0.0'
          - ruby: '2.5'
            puppet: '< 6.0.0'
          - ruby: '2.4'
            puppet: '< 8.0.0'
        puppet:
          - '< 6.0.0'
          - '< 7.0.0'
          - '< 8.0.0'
        ruby:
          - '2.4'
          - '2.5'
          - '2.6'
    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v2.4.0'

      - name: 'Set up Ruby'
        uses: 'ruby/setup-ruby@v1.94.0'
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Get full Ruby version
        id: full-ruby-version
        run: |
          echo ::set-output name=version::$(ruby -e 'puts RUBY_VERSION')

      - name: 'Cache Ruby'
        uses: 'actions/cache@v2.1.7'
        with:
          path: 'vendor/bundle'
          key: ${{ runner.os }}-${{ steps.full-ruby-version.outputs.version }}-v1-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.full-ruby-version.outputs.version }}-v1-gems-

      - name: 'Install ruby dependencies'
        env:
          PUPPET_GEM_VERSION: ${{ matrix.puppet }}
        run: |
          gem install bundler
          bundler --version
          bundle config path vendor/bundle
          bundle config set with 'development'
          bundle install --jobs 4 --retry 3

      - name: 'Versions'
        run: |
          ruby --version
          bundle exec puppet --version

      - name: 'Install fixtures'
        run: 'bundle exec rake spec_prep'

      - name: 'Run unit tests'
        run: 'bundle exec rake spec:simplecov'
